version: '3.1'

services:
  db:
    container_name: db
    env_file:
      - ./backend/.env
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - engineerchallenge:/var/lib/postgresql/data

  backend:
    container_name: backend
    env_file:
      - ./backend/.env
    build:
        context: ./backend/
    command: sh -c "yarn prisma generate && yarn start"
    volumes:
      - ./backend/:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    container_name: frontend
    env_file:
      - ./backend/.env
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  engineerchallenge:
  backend_node_modules:
  frontend_node_modules:
